language: R
addons:
  apt:
    packages:
      - libxml2-dev
      - libgsl0-dev
sudo: false
cache: packages
latex: false
warnings_are_errors: false
install:
    - R -e 'install.packages("devtools")'
    - R -e 'devtools::install_deps(dep = T)'
